export const SET_INDUSTRY_MAP_FILTERS = 'SET_INDUSTRY_MAP_FILTERS';
export const DELETE_INDUSTRY_MAP_FILTERS = 'DELETE_INDUSTRY_MAP_FILTERS';
export const RESET_INDUSTRY_MAP_FILTERS = 'RESET_INDUSTRY_MAP_FILTERS';
export const TRIGGER_INDUSTRY_MAP_FILTERS_RENDER =
  'TRIGGER_INDUSTRY_MAP_FILTERS_RENDER';
